### PR TITLE
fix(Inference): Account for self-referencial constraints

### LINKED ISSUE #549: fix(Extension inference): Allow loops
Blocks #497

### PR DESCRIPTION
**Pull request by croyzor**
Resolves #549

### CODE REVIEW

File: src/extension/infer.rs [hunk 1]
```diff
@@ -658,7 +658,20 @@ impl UnificationContext {
...
+                // should be instantiated to E rather than the empty set.
+                let solution = ExtensionSet::from_iter(self.get_constraints(&m).unwrap().iter().filter_map(|c| match c {
+                    Constraint::Plus(x, other_m) => {
+                        if &m == other_m {
+                            Some(x.clone())
+                        } else {
+                            None
+                        }
+                    }
+                    _ => None,
```
Comment (aborgna-q) [inline src/extension/infer.rs:672]:
```suggestion
                    Constraint::Plus(x, other_m) if &m == other_m => Some(x.clone()),
                    _ => None,
```

**Review by aborgna-q — APPROVED** [review]
LGTM

File: src/extension/infer.rs (hunk 1 above)
Comment (croyzor) [reply src/extension/infer.rs:672]: Yessss this is what I wanted 🎉
