### PR TITLE
Fix edge serialization not compacting the nodes

### LINKED ISSUE #202: Serialisation fails with copy before node
The following serialisation round-trip fails (you need to add `serde_json` for this particular example). Is it due to having the same input to both arguments?

```rust
let tp: Vec<SimpleType> = vec![ClassicType::bit().into(); 2];
let mut dfg = DFGBuilder::new(tp.clone(), tp.clone()).unwrap();
let mut params: [_; 2] = dfg.input_wires_arr();
for p in params.iter_mut() {
    *p = dfg
        .add_dataflow_op(LeafOp::Xor, [*p, *p])
        .unwrap()
        .out_wire(0);
}
let h = dfg.finish_hugr_with_outputs(params).unwrap();
// Nothing wrong here
h.validate().unwrap();

let ser = serde_json::to_vec(&h).unwrap();
// This fails
let _: Hugr = serde_json::from_slice(&ser).unwrap();
```

### PR DESCRIPTION
**Pull request by aborgna-q**
If a copy node made the op nodes non-contiguous, the edge serialization didn't translate the endpoints `Node`s.

This is a one-liner fix + a new check on the node index when deserializing + the previously-failing test.

Closes #202

### CODE REVIEW

File: src/hugr/serialize.rs [hunk 1]
```diff
@@ -330,4 +342,23 @@ pub mod test {
         // test equality on SerHugrV0 instead.
         assert_eq!(ser_roundtrip(&ser_hugr), ser_hugr);
     }
+
+    #[test]
+    fn dgf_roundtrip() -> Result<(), Box<dyn std::error::Error>> {
```
Comment (lmondada) [inline src/hugr/serialize.rs:347]: I'm being petty
```suggestion
    fn dfg_roundtrip() -> Result<(), Box<dyn std::error::Error>> {
```

**Review by lmondada — APPROVED** [review]
Thank you so much, it's super appreciated!! Would just fix the typo.
